name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Build
        run: mvn clean install -DskipTests

      - name: Analyze code
        run: mvn checkstyle:checkstyle
